### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by wsdflink** [adamzjk/Age-Gender-Pred#1]
Hi i tried to train your model , but failed with the following messages. Could you help me check out?Thx.

[AgePredModel] load_data: start loading...
[AgePredModel] load_data: Done! Get 0 for train and 0 for test!
[AgePredModel] load_data: loading finished !
[AgePredModel] train_model: Start training...
[train_model] Checkpoint Not Found, Train From Scratch!
[AgePredModel] Model has 12246k out of 12246k trainable params 

Start Epoch 1/32 ...
----------------
Traceback (most recent call last):
  File "/home/bob/wsdflink/Age-Gender-Pred/train.py", line 639, in <module>
    a.train_model()
  File "/home/bob/wsdflink/Age-Gender-Pred/train.py", line 378, in train_model
    epoch_gender_acc = epoch_gender_tp / self.dataset_sizes[phase]
ZeroDivisionError: float division by zero

Process finished with exit code 1

**Comment by naayaaa** [comment]
because u have no training images so the variable self.datasize[phase] = 0

**Comment by wsdflink** [comment]
thanks. could you please advise me where to download pretrained weight from url[pending]? i am interested in your research. thank you.

**Comment by wsdflink** [comment]
@adamzjk hi, i would like to ask how to prepare the training data. Using cleaned IMDB-WIKI dataset[1] for training? What does the 'cleaned' mean? How to train? Please help thanks.

**Comment by naayaaa** [comment]
@wsdflink 

1. **about pretrained weight**: sorry i dont have the appropriate weight atm.

2. **about how to prepare the training data**: u can either read the article[1] about the reason of massive mislabel and find a solution to it. or read my code in `preprocess.py`. 

in a nutshell u should:
- create a folder named "pics" in source dir
- put imdb images data in "pics/imdb"
- call `addlabels(data='imdb', clean=True);align_faces(clean = True);divideTrainVal()` in order to get train data

**Comment by wsdflink** [comment]
@adamzjk thanks. i followed your steps to prepare train pics successfully. And here is another problem i got:
/home/bob/anaconda3/bin/python3.6 /media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/train.py
[AgePredModel] load_data: start loading...
[AgePredModel] load_data: Done! Get 153769 for train and 0 for test!
[AgePredModel] load_data: loading finished !
[AgePredModel] train_model: Start training...
[train_model] Checkpoint Not Found, Train From Scratch!
[AgePredModel] Model has 12246k out of 12246k trainable params 

Start Epoch 1/32 ...
----------------
Traceback (most recent call last):
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/train.py", line 639, in <module>
    a.train_model()
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/train.py", line 316, in train_model
    gender_loss_perc = 100 * (gender_loss / loss).cpu().data.numpy()[0]
IndexError: too many indices for array

Process finished with exit code 1

**Comment by naayaaa** [comment]
I admit this is an uncorrected bug in my code.
**basically the code assumes you are running this code on GPU**, if u are running it on CPU. some data structure might not be the same, so we need to handle different data structures under different running hardware. 

**to solve this error, try delete [0] from** `gender_loss_perc = 100 * (gender_loss / loss).cpu().data.numpy()[0]`

**Comment by wsdflink** [comment]
@adamzjk Thanks. I can run train now. But whenever start to run Epoch 3/32, program exited with out of memory as follows. I use two 1080ti GPUs and 11G memory for each GPU. Could you please help?

/home/bob/anaconda3/bin/python3.6 /media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/train.py
[AgePredModel] load_data: start loading...
[AgePredModel] load_data: Done! Get 153329 for train and 8504 for test!
[AgePredModel] load_data: loading finished !
[AgePredModel] train_model: Start training...
[train_model] Checkpoint Not Found, Train From Scratch!
[AgePredModel] Model has 12246k out of 12246k trainable params 

Start Epoch 1/32 ...
----------------
|| 100.00% 153329/153329 || LOSS = 0.03 || DISTR% 0 : 86 : 14 || AMAE/AACC±2/GACC = 9.15 / 14.34% / 85.26% || LR 0.001 || ETA 0s || BEST 99.00 / 0.00% / 0.00% ||
--TRAIN 0/32 Done! || AMAE/AACC±2/GACC = 9.88 / 11.88% / 81.74%  || COST 660s
/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/train.py:280: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputs = Variable(inputs.cuda(), volatile=volatile)
/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/train.py:281: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  gender_true = Variable(gender_true.cuda(), volatile=volatile)
/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/train.py:283: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  age_cls_true = Variable(age_cls_true.cuda(), volatile=volatile)
|| 100.00% 8504/8504 || LOSS = 0.03 || DISTR% 0 : 88 : 12 || AMAE/AACC±2/GACC = 9.73 / 11.54% / 85.58% || LR 0.001 || ETA 0s || BEST 99.00 / 0.00% / 0.00% ||
--VAL 0/32 Done! || AMAE/AACC±2/GACC = 9.60 / 12.92% / 85.17%  || COST 40s
--New BEST FOUND!! ||  AMAE/AACC/AACC±2/GACC = 9.60 / 12.92% / 85.17%

Start Epoch 2/32 ...
----------------
|| 100.00% 153329/153329 || LOSS = 0.03 || DISTR% 0 : 92 : 8 || AMAE/AACC±2/GACC = 8.90 / 16.33% / 89.38% || LR 0.001 || ETA 0s || BEST 9.60 / 12.92% / 85.17% ||
--TRAIN 1/32 Done! || AMAE/AACC±2/GACC = 8.81 / 16.49% / 88.58%  || COST 112s
|| 100.00% 8504/8504 || LOSS = 0.02 || DISTR% 0 : 86 : 14 || AMAE/AACC±2/GACC = 8.14 / 16.67% / 88.14% || LR 0.001 || ETA 0s || BEST 9.60 / 12.92% / 85.17% ||
--VAL 1/32 Done! || AMAE/AACC±2/GACC = 7.98 / 21.27% / 90.59%  || COST 8s
--New BEST FOUND!! ||  AMAE/AACC/AACC±2/GACC = 7.98 / 21.27% / 90.59%

Start Epoch 3/32 ...
----------------
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/train.py", line 639, in <module>
    a.train_model()
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/train.py", line 294, in train_model
    gender_out, age_out = self.model(inputs)
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 41, in _worker
    output = module(*input, **kwargs)
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/agegenpredmodel.py", line 141, in forward
    last1 = self.get_resnet_convs_out(x)
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/agegenpredmodel.py", line 85, in get_resnet_convs_out
    x = self.resNet.layer2(x)   # out = [N, 128, 28, 28]
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/models/resnet.py", line 46, in forward
    self.stack4 = self.make_stack(512, layers[3], stride=2)
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1194, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/generic/THCStorage.cu:58

Process finished with exit code 1

**Comment by naayaaa** [comment]
**try reduce batch size**
The model only trains last fully connected layers on first **2** epochs, start from epoch **3**, the model start to train the whole network, which is likely to cause an OOM error.

**Comment by wsdflink** [comment]
@adamzjk Thanks. I got the weight after reducing batch size to 256 finally. When i want to evaluate a demo pic, program exited with the following error, please kindly help check?

/home/bob/anaconda3/bin/python3.6 /media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/evaluate.py
[evaluate] evaluating 0_1_JasonSudeikis.jpg
Traceback (most recent call last):
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/evaluate.py", line 155, in <module>
    name_contain_label=False)
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/evaluate.py", line 114, in eval_batch
    img, gen_pred, age_pred = eval_single(img, model)
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/evaluate.py", line 25, in eval_single
    return_info=True)
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/train.py", line 630, in getAgeGender
    preds = self.model.evaluate(faces)
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/agegenpredmodel.py", line 152, in evaluate
    gen_out, age_out = self.forward(face)
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/agegenpredmodel.py", line 141, in forward
    last1 = self.get_resnet_convs_out(x)
  File "/media/bob/4e329a02-a831-44a6-b8ce-0b6c922a2451/wsdflink/age_gender/Age-Gender-Pred/agegenpredmodel.py", line 79, in get_resnet_convs_out
    x = self.resNet.conv1(x)    # out = [N, 64, 112, 112]
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bob/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'weight'

Process finished with exit code 1

**Comment by naayaaa** [comment]
apparently this error occurs when a mismatch on data structure(CPU vs GPU) was found.

my code didnt cover this  because i done all the testing on CPU only, sorry, **try use `x = x.cuda()` and convert both model and data structure to GPU type.**

**Comment by wsdflink** [comment]
@adamzjk Thanks.
